### ISSUE TITLE
I ran installer and got error

### ISSUE THREAD

**Issue by tyeeman** [gentlecat/publisher#10]
I ran your go get command and got this - 

```
# cd C:\goWorkspace\src\github.com\russross\blackfriday; git pull --ff-only
From https://github.com/russross/blackfriday
   6d1ef89..a925a15  master           -> origin/master
 * [new branch]      less-go-versions -> origin/less-go-versions
   187c33f..3e56bb6  v2               -> origin/v2
 * [new branch]      v2-cleanup-ci    -> origin/v2-cleanup-ci
 * [new branch]      v2-fix-travis    -> origin/v2-fix-travis
 * [new branch]      v2-issue423-crlf -> origin/v2-issue423-crlf
 * [new tag]         v1.5.1           -> v1.5.1
 * [new tag]         v1.5.2           -> v1.5.2
 * [new tag]         v2.0.1           -> v2.0.1
Updating 6d1ef89..a925a15
error: Your local changes to the following files would be overwritten by merge:
        .travis.yml
        README.md
        block.go
        block_test.go
        html.go
        inline.go
        inline_test.go
        latex.go
        markdown.go
        testdata/Links, inline style.html
        testdata/Links, inline style.text
Please commit your changes or stash them before you merge.
Aborting
package github.com/russross/blackfriday: exit status 1
```
Do you know why? It's never happened during an install before.

**Comment by gentlecat** [comment]
Are you actually doing an install? From what you pasted it looks like you are trying to do a [git pull](https://www.git-scm.com/docs/git-pull) on a repository where you made changes. That's the warning it gives you.

If this is not a complete log, can you post all of it from the first command you run?

**Comment by tyeeman** [comment]
Yes, that's the full error I got during the install. I wonder if others were working on it when I was installing?

**Comment by tyeeman** [comment]
I think I found my problem and will try installing again. Can I run 
```
go get github.com/gentlecat/publisher
```
to install?

**Comment by gentlecat** [comment]
Yep, that should be the right command. Check https://github.com/gentlecat/publisher/blob/master/README.md as well.

**Comment by tyeeman** [comment]
OK, this time no problem installing. I thought I saw a description of more detail on the commands somewhere??

**Comment by tyeeman** [comment]
OK, command was simple. This works very nice, thanks! I mention 2 things - 

1. I added to the template `<!DOCTYPE html>` at the top. I ran into a problem on another project recently without this declaration.
2. I'm on Windows and here we use CRLF, which caused build problem error. I changed my .md files to LF only and build went without a problem. Is it easy to change your code to accept either?

**Comment by tyeeman** [comment]
I see this code - 
```
// PageContext contains actual content that gets sent to a template.
type PageContext struct {
	Title string
	Data  interface{} // Additional data that doesn't fit into any other field.
	// TODO: Perhaps look into moving fields defined below into `Data`:
	Name    string
	Content template.HTML
	Tags    []string
	Date    time.Time
}
```
mentions Tags, how do I use tags and categories? I really like to use these functions.

**Comment by gentlecat** [comment]
> I'm on Windows and here we use CRLF, which caused build problem error. I changed my .md files to LF only and build went without a problem. Is it easy to change your code to accept either?

Feel free to submit changes to support both, though I'm not quite sure what's causing problems.

> how do I use tags and categories?

Those aren't really used much. You can show them in templates, but there's currently no way to look up pages only with a specific tag or category.
